import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-black">
          <ul className="bg-[#1B1B1B] w-[70%] h-20 xl:w-[1100px] xl:h-[70px] m-auto rounded-xl flex justify-evenly items-center">
            <li>
              <Link
                className="text-[#9c9c9c]  p-4   font-roboto font-semibold"
                href={"/"}
              >
                Home
              </Link>
            </li>
            <li>
              <Link
                className="text-[#9c9c9c]  p-4  font-roboto font-semibold"
                href={"/casestudies"}
              >
                case studies
              </Link>
            </li>
            <li>
              <Link
                className="text-[#9c9c9c]  p-4   font-roboto font-semibold"
                href={"/recentworks"}
              >
                recent work
              </Link>
            </li>
          </ul>
        </div>

        {children}
      </body>
    </html>
  );
}
